"use client";

export interface SubCategory {
  name: string;
  slug: string;
  products: Array<{
    name: string;
    price: number;
    oldPrice?: number;
    image: string;
    badge?: string;
  }>;
  brands: string[];
  filters?: Record<string, string[]>;
}

export interface CategoryData {
  slug: string;
  name: string;
  icon: string;
  image: string;
  description: string;
  subcategories: SubCategory[];
}

export const shopCategoriesData: Record<string, CategoryData> = {
  "mode-homme": {
    slug: "mode-homme",
    name: "Mode Homme",
    icon: "👔",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&q=80",
    description: "Vetements, costumes et accessoires pour homme",
    subcategories: [
        { name: "Vetements", slug: "mode-homme.vetements", products: [], brands: ["Nike","Adidas","Zara"] },
        { name: "T-shirts", slug: "mode-homme.t-shirts", products: [], brands: ["Nike","Adidas","Zara"] },
        { name: "Chemises", slug: "mode-homme.chemises", products: [], brands: ["Nike","Adidas","Zara"] },
        { name: "Pantalons & jeans", slug: "mode-homme.pantalons-jeans", products: [], brands: ["Nike","Adidas","Zara"] },
        { name: "Shorts", slug: "mode-homme.shorts", products: [], brands: ["Nike","Adidas","Zara"] },
        { name: "Vestes & manteaux", slug: "mode-homme.vestes-manteaux", products: [], brands: ["Nike","Adidas","Zara"] },
        { name: "Costumes", slug: "mode-homme.costumes", products: [], brands: ["Nike","Adidas","Zara"] },
        { name: "Sweats & pulls", slug: "mode-homme.sweats-pulls", products: [], brands: ["Nike","Adidas","Zara"] },
        { name: "Sous-vetements", slug: "mode-homme.sous-vetements", products: [], brands: ["Nike","Adidas","Zara"] },
        { name: "Sport", slug: "mode-homme.sport", products: [], brands: ["Nike","Adidas","Zara"] },
        { name: "Accessoires", slug: "mode-homme.accessoires", products: [], brands: ["Nike","Adidas","Zara"] },
        { name: "Montres", slug: "mode-homme.montres", products: [], brands: ["Nike","Adidas","Zara"] },
        { name: "Sacs", slug: "mode-homme.sacs", products: [], brands: ["Nike","Adidas","Zara"] },
    ],
  },
  "mode-femme": {
    slug: "mode-femme",
    name: "Mode Femme",
    icon: "👗",
    image: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=600&q=80",
    description: "Robes, hauts, lingerie et mode feminine",
    subcategories: [
        { name: "Vetements", slug: "mode-femme.vetements", products: [], brands: ["Zara","H&M","Mango"] },
        { name: "Robes", slug: "mode-femme.robes", products: [], brands: ["Zara","H&M","Mango"] },
        { name: "Tops & blouses", slug: "mode-femme.tops-blouses", products: [], brands: ["Zara","H&M","Mango"] },
        { name: "Chemises", slug: "mode-femme.chemises", products: [], brands: ["Zara","H&M","Mango"] },
        { name: "Pantalons & jeans", slug: "mode-femme.pantalons-jeans", products: [], brands: ["Zara","H&M","Mango"] },
        { name: "Jupes", slug: "mode-femme.jupes", products: [], brands: ["Zara","H&M","Mango"] },
        { name: "Shorts", slug: "mode-femme.shorts", products: [], brands: ["Zara","H&M","Mango"] },
        { name: "Vestes & manteaux", slug: "mode-femme.vestes-manteaux", products: [], brands: ["Zara","H&M","Mango"] },
        { name: "Pulls & sweats", slug: "mode-femme.pulls-sweats", products: [], brands: ["Zara","H&M","Mango"] },
        { name: "Lingerie", slug: "mode-femme.lingerie", products: [], brands: ["Zara","H&M","Mango"] },
        { name: "Sport", slug: "mode-femme.sport", products: [], brands: ["Zara","H&M","Mango"] },
        { name: "Chaussures", slug: "mode-femme.chaussures", products: [], brands: ["Zara","H&M","Mango"] },
        { name: "Sacs", slug: "mode-femme.sacs", products: [], brands: ["Zara","H&M","Mango"] },
        { name: "Accessoires", slug: "mode-femme.accessoires", products: [], brands: ["Zara","H&M","Mango"] },
    ],
  },
  "parfums-cosmetiques": {
    slug: "parfums-cosmetiques",
    name: "Parfums & Cosmetiques",
    icon: "💄",
    image: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=600&q=80",
    description: "Parfums, maquillage et soins beaute",
    subcategories: [
        { name: "Parfums homme", slug: "parfums-cosmetiques.parfums-homme", products: [], brands: ["Chanel","Dior","Tom Ford"] },
        { name: "Parfums femme", slug: "parfums-cosmetiques.parfums-femme", products: [], brands: ["Chanel","Dior","Tom Ford"] },
        { name: "Maquillage", slug: "parfums-cosmetiques.maquillage", products: [], brands: ["Chanel","Dior","Tom Ford"] },
        { name: "Soins visage", slug: "parfums-cosmetiques.soins-visage", products: [], brands: ["Chanel","Dior","Tom Ford"] },
        { name: "Soins corps", slug: "parfums-cosmetiques.soins-corps", products: [], brands: ["Chanel","Dior","Tom Ford"] },
        { name: "Soins cheveux", slug: "parfums-cosmetiques.soins-cheveux", products: [], brands: ["Chanel","Dior","Tom Ford"] },
        { name: "Solaire", slug: "parfums-cosmetiques.solaire", products: [], brands: ["Chanel","Dior","Tom Ford"] },
        { name: "Accessoires beaute", slug: "parfums-cosmetiques.accessoires-beaute", products: [], brands: ["Chanel","Dior","Tom Ford"] },
    ],
  },
  "chaussures": {
    slug: "chaussures",
    name: "Chaussures",
    icon: "👟",
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80",
    description: "Sneakers, bottes, souliers et sandales",
    subcategories: [
        { name: "Sneakers", slug: "chaussures.sneakers", products: [], brands: ["Nike","Adidas","Puma"] },
        { name: "Bottines & boots", slug: "chaussures.bottines-boots", products: [], brands: ["Nike","Adidas","Puma"] },
        { name: "Souliers", slug: "chaussures.souliers", products: [], brands: ["Nike","Adidas","Puma"] },
        { name: "Sandales", slug: "chaussures.sandales", products: [], brands: ["Nike","Adidas","Puma"] },
        { name: "Mocassins", slug: "chaussures.mocassins", products: [], brands: ["Nike","Adidas","Puma"] },
        { name: "Chaussures de sport", slug: "chaussures.chaussures-sport", products: [], brands: ["Nike","Adidas","Puma"] },
        { name: "Chaussures de travail", slug: "chaussures.chaussures-travail", products: [], brands: ["Nike","Adidas","Puma"] },
    ],
  },
  "accessoires": {
    slug: "accessoires",
    name: "Accessoires",
    icon: "🕶️",
    image: "https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=600&q=80",
    description: "Montres, bijoux, sacs et lunettes",
    subcategories: [
        { name: "Montres", slug: "accessoires.montres", products: [], brands: ["Ray-Ban","Oakley","Casio"] },
        { name: "Bijoux", slug: "accessoires.bijoux", products: [], brands: ["Ray-Ban","Oakley","Casio"] },
        { name: "Lunettes de soleil", slug: "accessoires.lunettes-soleil", products: [], brands: ["Ray-Ban","Oakley","Casio"] },
        { name: "Sacs a main", slug: "accessoires.sacs-main", products: [], brands: ["Ray-Ban","Oakley","Casio"] },
        { name: "Portefeuilles", slug: "accessoires.portefeuilles", products: [], brands: ["Ray-Ban","Oakley","Casio"] },
        { name: "Ceintures", slug: "accessoires.ceintures", products: [], brands: ["Ray-Ban","Oakley","Casio"] },
        { name: "Echarpes", slug: "accessoires.echarpes", products: [], brands: ["Ray-Ban","Oakley","Casio"] },
        { name: "Casquettes", slug: "accessoires.casquettes", products: [], brands: ["Ray-Ban","Oakley","Casio"] },
    ],
  },
  "electronique-hightech": {
    slug: "electronique-hightech",
    name: "Electronique & High-Tech",
    icon: "📱",
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&q=80",
    description: "Smartphones, ordinateurs et gadgets",
    subcategories: [
        { name: "Ordinateurs", slug: "electronique-hightech.ordinateurs", products: [], brands: ["Apple","Samsung","Sony"] },
        { name: "Tablettes", slug: "electronique-hightech.tablettes", products: [], brands: ["Apple","Samsung","Sony"] },
        { name: "Ecouteurs & casques", slug: "electronique-hightech.ecouteurs-casques", products: [], brands: ["Apple","Samsung","Sony"] },
        { name: "Enceintes", slug: "electronique-hightech.enceintes", products: [], brands: ["Apple","Samsung","Sony"] },
        { name: "Appareils photo", slug: "electronique-hightech.appareils-photo", products: [], brands: ["Apple","Samsung","Sony"] },
        { name: "Drones", slug: "electronique-hightech.drones", products: [], brands: ["Apple","Samsung","Sony"] },
        { name: "Accessoires PC", slug: "electronique-hightech.accessoires-pc", products: [], brands: ["Apple","Samsung","Sony"] },
    ],
  },
  "telephones-accessoires": {
    slug: "telephones-accessoires",
    name: "Telephones & Accessoires",
    icon: "📲",
    image: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&q=80",
    description: "Coques, chargeurs et accessoires mobile",
    subcategories: [
        { name: "Coques & etuis", slug: "telephones-accessoires.coques-etuis", products: [], brands: ["Apple","Samsung","Anker"] },
        { name: "Chargeurs", slug: "telephones-accessoires.chargeurs", products: [], brands: ["Apple","Samsung","Anker"] },
        { name: "Cables", slug: "telephones-accessoires.cables", products: [], brands: ["Apple","Samsung","Anker"] },
        { name: "Supports", slug: "telephones-accessoires.supports", products: [], brands: ["Apple","Samsung","Anker"] },
        { name: "Ecrans de protection", slug: "telephones-accessoires.ecrans-protection", products: [], brands: ["Apple","Samsung","Anker"] },
        { name: "Powerbanks", slug: "telephones-accessoires.powerbanks", products: [], brands: ["Apple","Samsung","Anker"] },
        { name: "Accessoires tablette", slug: "telephones-accessoires.accessoires-tablette", products: [], brands: ["Apple","Samsung","Anker"] },
    ],
  },
  "maison": {
    slug: "maison",
    name: "Maison & Decor",
    icon: "🏠",
    image: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=600&q=80",
    description: "Meubles, decoration et linge de maison",
    subcategories: [
        { name: "Meubles", slug: "maison.meubles", products: [], brands: ["IKEA","Maisons du Monde","H&M Home"] },
        { name: "Eclairage", slug: "maison.eclairage", products: [], brands: ["IKEA","Maisons du Monde","H&M Home"] },
        { name: "Textile maison", slug: "maison.textile-maison", products: [], brands: ["IKEA","Maisons du Monde","H&M Home"] },
        { name: "Cuisine", slug: "maison.cuisine", products: [], brands: ["IKEA","Maisons du Monde","H&M Home"] },
        { name: "Salle de bain", slug: "maison.salle-de-bain", products: [], brands: ["IKEA","Maisons du Monde","H&M Home"] },
        { name: "Decoration", slug: "maison.decoration", products: [], brands: ["IKEA","Maisons du Monde","H&M Home"] },
        { name: "Rangement", slug: "maison.rangement", products: [], brands: ["IKEA","Maisons du Monde","H&M Home"] },
        { name: "Jardin interieur", slug: "maison.jardin-interieur", products: [], brands: ["IKEA","Maisons du Monde","H&M Home"] },
    ],
  },
  "sport-loisirs": {
    slug: "sport-loisirs",
    name: "Sport & Loisirs",
    icon: "⚽",
    image: "https://images.unsplash.com/photo-1461896836934-bd45ba48a084?w=600&q=80",
    description: "Fitness, camping et equipement sportif",
    subcategories: [
        { name: "Fitness", slug: "sport-loisirs.fitness", products: [], brands: ["Nike","Adidas","Puma"] },
        { name: "Musculation", slug: "sport-loisirs.musculation", products: [], brands: ["Nike","Adidas","Puma"] },
        { name: "Football", slug: "sport-loisirs.football", products: [], brands: ["Nike","Adidas","Puma"] },
        { name: "Basketball", slug: "sport-loisirs.basketball", products: [], brands: ["Nike","Adidas","Puma"] },
        { name: "Cyclisme", slug: "sport-loisirs.cyclisme", products: [], brands: ["Nike","Adidas","Puma"] },
        { name: "Camping", slug: "sport-loisirs.camping", products: [], brands: ["Nike","Adidas","Puma"] },
        { name: "Piscine", slug: "sport-loisirs.piscine", products: [], brands: ["Nike","Adidas","Puma"] },
        { name: "Yoga", slug: "sport-loisirs.yoga", products: [], brands: ["Nike","Adidas","Puma"] },
        { name: "Randonnee", slug: "sport-loisirs.randonnee", products: [], brands: ["Nike","Adidas","Puma"] },
    ],
  },
  "enfants-jouets": {
    slug: "enfants-jouets",
    name: "Enfants & Jouets",
    icon: "🧸",
    image: "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=600&q=80",
    description: "Jouets, vetements et articles pour enfants",
    subcategories: [
        { name: "Jouets educatifs", slug: "enfants-jouets.jouets-educatifs", products: [], brands: ["Lego","Fisher-Price","Hasbro"] },
        { name: "Jeux de societe", slug: "enfants-jouets.jeux-societe", products: [], brands: ["Lego","Fisher-Price","Hasbro"] },
        { name: "Poupees", slug: "enfants-jouets.poupees", products: [], brands: ["Lego","Fisher-Price","Hasbro"] },
        { name: "Figurines", slug: "enfants-jouets.figurines", products: [], brands: ["Lego","Fisher-Price","Hasbro"] },
        { name: "Puzzles", slug: "enfants-jouets.puzzles", products: [], brands: ["Lego","Fisher-Price","Hasbro"] },
        { name: "Jouets d'exterieur", slug: "enfants-jouets.jouets-exterieur", products: [], brands: ["Lego","Fisher-Price","Hasbro"] },
        { name: "Peluches", slug: "enfants-jouets.peluches", products: [], brands: ["Lego","Fisher-Price","Hasbro"] },
    ],
  },
  "bricolage-outils": {
    slug: "bricolage-outils",
    name: "Bricolage & Outils",
    icon: "🔧",
    image: "https://images.unsplash.com/photo-1504148455328-c376907d081c?w=600&q=80",
    description: "Outils, outillage et materiel de bricolage",
    subcategories: [
        { name: "Outils a main", slug: "bricolage-outils.outils-main", products: [], brands: ["Bosch","Makita","DeWalt"] },
        { name: "Outils electriques", slug: "bricolage-outils.outils-electriques", products: [], brands: ["Bosch","Makita","DeWalt"] },
        { name: "Visserie & fixation", slug: "bricolage-outils.visserie-fixation", products: [], brands: ["Bosch","Makita","DeWalt"] },
        { name: "Peinture", slug: "bricolage-outils.peinture", products: [], brands: ["Bosch","Makita","DeWalt"] },
        { name: "Plomberie", slug: "bricolage-outils.plomberie", products: [], brands: ["Bosch","Makita","DeWalt"] },
        { name: "Electricite", slug: "bricolage-outils.electricite", products: [], brands: ["Bosch","Makita","DeWalt"] },
        { name: "Soudure", slug: "bricolage-outils.soudure", products: [], brands: ["Bosch","Makita","DeWalt"] },
        { name: "Mesure", slug: "bricolage-outils.mesure", products: [], brands: ["Bosch","Makita","DeWalt"] },
    ],
  },
  "auto-moto": {
    slug: "auto-moto",
    name: "Auto & Moto",
    icon: "🚗",
    image: "https://raw.githubusercontent.com/Uzalus/UZALUSv2/main/public/images/auto-banner.png",
    description: "Pieces auto, accessoires et equipements vehicules",
    subcategories: [
        { name: "Pieces auto", slug: "auto-moto.pieces-auto", products: [], brands: ["Bosch","Castrol","Michelin"] },
        { name: "Accessoires auto", slug: "auto-moto.accessoires-auto", products: [], brands: ["Bosch","Castrol","Michelin"] },
        { name: "Entretien", slug: "auto-moto.entretien", products: [], brands: ["Bosch","Castrol","Michelin"] },
        { name: "Electricite auto", slug: "auto-moto.electricite-auto", products: [], brands: ["Bosch","Castrol","Michelin"] },
        { name: "Carrosserie", slug: "auto-moto.carrosserie", products: [], brands: ["Bosch","Castrol","Michelin"] },
        { name: "Tuning", slug: "auto-moto.tuning", products: [], brands: ["Bosch","Castrol","Michelin"] },
        { name: "Accessoires moto", slug: "auto-moto.accessoires-moto", products: [], brands: ["Bosch","Castrol","Michelin"] },
        { name: "Equipement moto", slug: "auto-moto.equipement-moto", products: [], brands: ["Bosch","Castrol","Michelin"] },
    ],
  },
  "animaux": {
    slug: "animaux",
    name: "Animaux",
    icon: "🐾",
    image: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&q=80",
    description: "Accessoires et alimentation pour animaux",
    subcategories: [
        { name: "Alimentation chiens", slug: "animaux.alimentation-chiens", products: [], brands: ["Royal Canin","Purina","Whiskas"] },
        { name: "Alimentation chats", slug: "animaux.alimentation-chats", products: [], brands: ["Royal Canin","Purina","Whiskas"] },
        { name: "Accessoires chiens", slug: "animaux.accessoires-chiens", products: [], brands: ["Royal Canin","Purina","Whiskas"] },
        { name: "Accessoires chats", slug: "animaux.accessoires-chats", products: [], brands: ["Royal Canin","Purina","Whiskas"] },
        { name: "Soins & hygiene", slug: "animaux.soins-hygiene", products: [], brands: ["Royal Canin","Purina","Whiskas"] },
        { name: "Bacs & cages", slug: "animaux.bacs-cages", products: [], brands: ["Royal Canin","Purina","Whiskas"] },
        { name: "Aquariophilie", slug: "animaux.aquariophilie", products: [], brands: ["Royal Canin","Purina","Whiskas"] },
    ],
  },
  "alimentation-epicerie": {
    slug: "alimentation-epicerie",
    name: "Alimentation & Epicerie",
    icon: "🍜",
    image: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=600&q=80",
    description: "Produits alimentaires et epicerie",
    subcategories: [
        { name: "Boissons", slug: "alimentation-epicerie.boissons", products: [], brands: ["Nestle","Knorr","Heinz"] },
        { name: "Epices & condiments", slug: "alimentation-epicerie.epices-condiments", products: [], brands: ["Nestle","Knorr","Heinz"] },
        { name: "Produits bio", slug: "alimentation-epicerie.produits-bio", products: [], brands: ["Nestle","Knorr","Heinz"] },
        { name: "Snacks", slug: "alimentation-epicerie.snacks", products: [], brands: ["Nestle","Knorr","Heinz"] },
        { name: "Cereales", slug: "alimentation-epicerie.cereales", products: [], brands: ["Nestle","Knorr","Heinz"] },
        { name: "Conserves", slug: "alimentation-epicerie.conserves", products: [], brands: ["Nestle","Knorr","Heinz"] },
        { name: "Huiles & vinaigres", slug: "alimentation-epicerie.huiles-vinaigres", products: [], brands: ["Nestle","Knorr","Heinz"] },
        { name: "Produits du monde", slug: "alimentation-epicerie.produits-monde", products: [], brands: ["Nestle","Knorr","Heinz"] },
    ],
  },
  "bagagerie-voyage": {
    slug: "bagagerie-voyage",
    name: "Bagagerie & Voyage",
    icon: "🧳",
    image: "https://images.unsplash.com/photo-1547949003-9792a18a2601?w=600&q=80",
    description: "Valises, sacs de voyage et accessoires",
    subcategories: [
        { name: "Valises rigides", slug: "bagagerie-voyage.valises-rigides", products: [], brands: ["Samsonite","Eastpak","American Tourister"] },
        { name: "Valises souples", slug: "bagagerie-voyage.valises-souples", products: [], brands: ["Samsonite","Eastpak","American Tourister"] },
        { name: "Sacs de voyage", slug: "bagagerie-voyage.sacs-voyage", products: [], brands: ["Samsonite","Eastpak","American Tourister"] },
        { name: "Sacs a dos", slug: "bagagerie-voyage.sacs-dos", products: [], brands: ["Samsonite","Eastpak","American Tourister"] },
        { name: "Trousse de toilette", slug: "bagagerie-voyage.trousse-toilette", products: [], brands: ["Samsonite","Eastpak","American Tourister"] },
        { name: "Accessoires voyage", slug: "bagagerie-voyage.accessoires-voyage", products: [], brands: ["Samsonite","Eastpak","American Tourister"] },
    ],
  },
  "bureau-fournitures": {
    slug: "bureau-fournitures",
    name: "Bureau & Fournitures",
    icon: "📚",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&q=80",
    description: "Fournitures de bureau et papeterie",
    subcategories: [
        { name: "Papeterie", slug: "bureau-fournitures.papeterie", products: [], brands: ["Staedtler","Post-it","3M"] },
        { name: "Classement", slug: "bureau-fournitures.classement", products: [], brands: ["Staedtler","Post-it","3M"] },
        { name: "Ecriture", slug: "bureau-fournitures.ecriture", products: [], brands: ["Staedtler","Post-it","3M"] },
        { name: "Imprimantes", slug: "bureau-fournitures.imprimantes", products: [], brands: ["Staedtler","Post-it","3M"] },
        { name: "Chaises de bureau", slug: "bureau-fournitures.chaises-bureau", products: [], brands: ["Staedtler","Post-it","3M"] },
        { name: "Eclairage bureau", slug: "bureau-fournitures.eclairage-bureau", products: [], brands: ["Staedtler","Post-it","3M"] },
    ],
  },
  "emballage": {
    slug: "emballage",
    name: "Emballage",
    icon: "📦",
    image: "https://images.unsplash.com/photo-1607166452427-7e4477c5e768?w=600&q=80",
    description: "Emballages, cartons et materiel d'emballage",
    subcategories: [
        { name: "Cartons", slug: "emballage.cartons", products: [], brands: ["3M","Scotch","DHL"] },
        { name: "Enveloppes", slug: "emballage.enveloppes", products: [], brands: ["3M","Scotch","DHL"] },
        { name: "Adhesifs", slug: "emballage.adhesifs", products: [], brands: ["3M","Scotch","DHL"] },
        { name: "Film bulle", slug: "emballage.film-bulle", products: [], brands: ["3M","Scotch","DHL"] },
        { name: "Sacs", slug: "emballage.sacs", products: [], brands: ["3M","Scotch","DHL"] },
        { name: "Etiquettes", slug: "emballage.etiquettes", products: [], brands: ["3M","Scotch","DHL"] },
        { name: "Ruban adhesif", slug: "emballage.ruban-adhesif", products: [], brands: ["3M","Scotch","DHL"] },
    ],
  },
  "enfant": {
    slug: "enfant",
    name: "Bebe & Enfant",
    icon: "👶",
    image: "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=600&q=80",
    description: "Articles pour bebes et jeunes enfants",
    subcategories: [
        { name: "Vetements bebe", slug: "enfant.vetements-bebe", products: [], brands: ["Pampers","Avent","Babybjorn"] },
        { name: "Couches", slug: "enfant.couches", products: [], brands: ["Pampers","Avent","Babybjorn"] },
        { name: "Alimentation bebe", slug: "enfant.alimentation-bebe", products: [], brands: ["Pampers","Avent","Babybjorn"] },
        { name: "Securite", slug: "enfant.securite", products: [], brands: ["Pampers","Avent","Babybjorn"] },
        { name: "Poussettes", slug: "enfant.poussettes", products: [], brands: ["Pampers","Avent","Babybjorn"] },
        { name: "Sieges auto", slug: "enfant.sieges-auto", products: [], brands: ["Pampers","Avent","Babybjorn"] },
        { name: "Jouets bebe", slug: "enfant.jouets-bebe", products: [], brands: ["Pampers","Avent","Babybjorn"] },
        { name: "Chambre bebe", slug: "enfant.chambre-bebe", products: [], brands: ["Pampers","Avent","Babybjorn"] },
    ],
  },
};
